kind: Deployment
apiVersion: apps/v1
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 4
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: lerndevops/petclinic:bno
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003
