---
- hosts: qa
  tasks:
  - name: deploy petclinic docker container
    docker_container:
      image: ravuris78/petclinic:{{build}}
      name: petclinic
      state: started
      auto_remove: true
      exposed_ports:
      - 8080
      ports:
        - "8080:8080"